language: objective-c

osx_image: xcode8.3

cache:
- bundler
- cocoapods

before_install:
- bundle install

script:
- xcodebuild -version
- bundle exec danger --dangerfile=iOS-Template/CodeDoesGood-iOSTemplate/Dangerfile
