language: objective-c

osx_image: xcode8.3

cache:
- bundler
- cocoapods

before_install:
- bundle install
- cd iOS-Template/CodeDoesGood-iOSTemplate

script:
- xcodebuild -version
- bundle exec danger --dangerfile=/Users/travis/build/vitalii-tym/iOS-Template/iOS-Template/CodeDoesGood-iOSTemplate/