language: objective-c

osx_image: xcode8.3

cache:
- bundler
- cocoapods

before_install:
- bundle install
- cd iOS-Template/CodeDoesGood-iOSTemplate
- bundle exec pod keys set NetworkAPIToken $NETWORKAPITOKEN

script:
- xcodebuild -version
- travis_retry xcodebuild -workspace CodeDoesGood-iOSTemplate.xcworkspace -scheme 'CodeDoesGood-iOSTemplate' -sdk iphonesimulator -destination "name=iPhone SE" test
- cd ../..
- bundle exec danger --dangerfile=iOS-Template/CodeDoesGood-iOSTemplate/Dangerfile