language: objective-c

osx_image: xcode8.3

cache:
- bundler
- cocoapods

before_install:
- bundle install
- cd iOS-Template/CodeDoesGood-iOSTemplate

script:
- xcodebuild -version
- xcodebuild -workspace CodeDoesGood-iOSTemplate.xcworkspace -scheme 'CodeDoesGood-iOSTemplate' -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 7" test
- bundle exec danger --dangerfile=/iOS-Template/CodeDoesGood-iOSTemplate
