# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CodeDoesGood-iOSTemplate' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CodeDoesGood-iOSTemplate
  pod 'SwiftGen'
  pod 'CocoaLumberjack/Swift'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Reusable'
  pod 'ReachabilitySwift', '~> 3'

  plugin 'cocoapods-keys', {
    :project => "CodeDoesGood-iOSTemplate",
    :keys => [
    "NetworkAPIToken"
  ]}

  target 'CodeDoesGood-iOSTemplateTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CodeDoesGood-iOSTemplateUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
